# -*- coding: utf-8 -*-
"""todo_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7ZfOVYiYinnTZvUJ9YEfbRCATOuk5E_
"""

import json # ファイルの保存、読み込み
import os # ファイルの存在確認

todo_list = []
FILE_NAME = "todo_data.json" # データを保存するファイル
priority_map = {"高": 1, "中": 2, "低": 3}

# データ永続化機能
# タスクリストをファイルに保存する
def save_tasks():

  try:
    with open(FILE_NAME, 'w', encoding='utf-8') as f: # 書き込み
      json.dump(todo_list, f, ensure_ascii=False, indent=4) # 保存処理
    print(f"\n✅ タスクリストを {FILE_NAME} に保存しました。")
  except Exception as e:
    print(f"⚠️ ファイル保存中にエラーが発生しました: {e}")

# タスクリストを読み込み、todo_listに格納
def load_tasks():

  global todo_list # 編集準備

  if os.path.exists(FILE_NAME): # ファイル存在確認
    try:
      with open(FILE_NAME, 'r', encoding='utf-8') as f: # 読み込み
        data = json.load(f)
        if isinstance(data, list): # 形式確認(オブジェクト, データ型)
          for item in data:
            if isinstance(item, str):
              todo_list.append({"name": item, "priority": "中"})
            elif isinstance(item, dict) and "name" in item:
              todo_list.append(item)
          print(f"📂 {FILE_NAME} からタスクを読み込みました。")
        else:
          print(f"⚠️ ファイルの内容がリスト形式ではありません。新しいリストを開始します。")
    except Exception as e:
      print(f"⚠️ ファイル読み込み中にエラーが発生しました: {e}")
  else:
    print("To-Doファイルが見つかりません。新しいリストを開始します。")

# タスクを追加
def add_task(task_name, priority):

  new_task = {"name": task_name, "priority": priority}
  todo_list.append(new_task)
  print(f"\n✅ タスク「{task_name}」(優先度: {priority})を追加しました。")

# タスク一覧表示
def view_tasks():

  if not todo_list:
    print("リストは空です。タスクはありません。")
    return []

  # ソート処理のためのキー関数
  def get_priority_value(task):
      priority_str = task.get("priority", "中") # 値を取得、なければ「中」に設定
      return priority_map.get(priority_str, 99)

  # 並べ替え処理の実行
  sorted_tasks = sorted(todo_list, key=get_priority_value)
  print("\n--- 現在の To-Do リスト (優先度順) ---")

  # 並べ替えたリストを表示
  for index, task in enumerate(sorted_tasks):
    task_name = task["name"]
    task_priority = task["priority"]

    print(f"{index + 1}. [{task_priority}] {task_name}")
  print("---------------------------------------\n")

  # 並べ替えたリストを呼び出し元に返す
  return sorted_tasks

# タスクを完了(削除)する
def complete_task(task_number_str, sorted_list):

  try:
    task_number = int(task_number_str)
    task_to_delete = sorted_list[task_number - 1] # タスク番号に対応
    completed_task_name = task_to_delete["name"]
    todo_list.remove(task_to_delete) # 削除
    print(f"\n✅ タスク「{completed_task_name}」を完了し、リストから削除しました。")

  except IndexError:
    print("⚠️ エラー: その番号のタスクは存在しません。")
  except ValueError:
    print("⚠️ エラー: タスク番号は整数で指定してください。")
  except Exception as e:
    print(f"⚠️ 予期せぬエラーが発生しました: {e}")

# メインメニュー
def main_menu():

  load_tasks()

  while True: # 無限ループ
    print("\n==================================")
    print("    To-Do リスト管理ツール (CLI)")
    print("==================================")
    print("1. タスクを追加")
    print("2. タスク一覧を表示")
    print("3. タスクを完了（削除）")
    print("4. 終了")

    choice = input("操作を選択してください (1-4): ") # 文字列を取得

    if choice == '1':
      task_name = input("追加するタスク名を入力してください: ")
      if task_name:
        priority_options = {"1": "高", "2": "中", "3": "低"}
        print("優先度を選択してください:")
        print("1: 高")
        print("2: 中")
        print("3: 低")
        priority_choice = input("優先度 (1, 2, 3) を入力: ").strip()
        priority = priority_options.get(priority_choice, "中") # デフォルトは「中」
        add_task(task_name, priority)

    elif choice == '2':
      view_tasks()

    elif choice == '3':
      sorted_list = view_tasks()
      if sorted_list:
        task_num_str = input("完了するタスクの番号を入力してください: ").strip()
        complete_task(task_num_str, sorted_list)

    elif choice == '4':
      save_tasks()
      print("\n👋 ツールを終了します。お疲れ様でした！")
      break

    else:
      print("\n⚠️ 無効な選択です。1から4の数字を入力してください。")

# プログラムのエントリーポイント
if __name__ == "__main__":
  main_menu()

